# -*- coding: utf-8 -*-
"""nlp-stemming-lemmatization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p6uPKuyPSlgfnodw54IILf1NyVS4Ldgx
"""

import nltk
from nltk.stem.porter import PorterStemmer
from nltk import word_tokenize

nltk.download('punkt_tab')

text1 = "walk walks walking walked"
text2 = "India has been a federal republic since 1950, governed through a democratic parliamentary system. It is a pluralistic, multilingual and multi-ethnic society. India's population grew from 361 million in 1951 to over 1.4 billion in 2023"

# stemming
ps = PorterStemmer()
def ps_stemming(text):
  word_tokens = word_tokenize(text)
  word_stems = []
  for word in word_tokens:
    word_stems.append(ps.stem(word))
  return word_tokens,word_stems


word_tokens,word_stems = ps_stemming(text1)
print(word_tokens)
print(word_stems)


word_tokens,word_stems = ps_stemming(text2)
print(word_tokens)
print(word_stems)

# lemmatization
from nltk.stem import WordNetLemmatizer
from nltk import word_tokenize
nltk.download('wordnet')
lemma = WordNetLemmatizer()

def lemmatizing(text):
  # first remove all punctuations
  import string
  all_puncs = string.punctuation

  text_no_puncs = text.translate(str.maketrans('','',all_puncs))

  print(f'Word--->Lemma')
  for word in word_tokenize(text_no_puncs):
    lemmatized = lemma.lemmatize(word,pos='v')
    print(f'{word}--->{lemmatized}')


print(lemmatizing(text2))

