# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KaPbB2y3gi6KIwjUBwVhz4TlHsJrGa2i
"""

import spacy

nlp = spacy.load('en_core_web_sm')

doc = nlp('I will google about facebook')

doc.text

doc[0]

doc[0].pos_

pos = {}
for word in doc:
  pos.update({word:word.pos_})
pos

