# -*- coding: utf-8 -*-
"""data_augmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sLWVtNue4xRejpyLEVuIs8u51cyzz0mY
"""

# why data augmentation:
# 1) to reduce overfitting: if our images has only one type of image eg: a cat looking at left and we feed it data of cat looking right during
#   test then it might not identify it
# 2) to increase data if limited

import cv2
import matplotlib.pyplot as plt
import numpy as np
import tensorflow
from tensorflow import keras
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img

img = image.load_img('/content/dog_test.png',target_size=(300,300))

img

datagen = ImageDataGenerator(
    rotation_range=30,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    width_shift_range=0.2,
    height_shift_range=0.2
)

img = img_to_array(img)

img.shape

image_reshaped = img.reshape(1,300,300,3)

i = 0
for i in datagen.flow(image_reshaped,batch_size=1,save_to_dir='/content/images'):
  i = i + 1
  if i == 10:
    break

