# -*- coding: utf-8 -*-
"""functional-model-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E_jhzMo2czmkrGo3MNvktLgYtjiwWpx7
"""

import tensorflow
from tensorflow import keras
from keras.models import Model
from keras.layers import *

x = Input(shape=(3,))

hidden1 = Dense(128,activation='relu')(x)

hidden2 = Dense(64,activation='relu')(hidden1)

output1 = Dense(1,activation='linear',)(hidden2)
output2 = Dense(1,activation='sigmoid')(hidden2)

model = Model(inputs=x,outputs=[output1,output2])

from keras.utils import plot_model

plot_model(model)

