# -*- coding: utf-8 -*-
"""Lenet-architecture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gUEFQ2Re3RWMV_mZuKUn3KC24C5dLBIO
"""

import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Conv2D, AveragePooling2D, Flatten, Dense
from keras.datasets import mnist

(X_train,y_train),(X_test,y_test) = mnist.load_data()

model = Sequential()

model.add(Conv2D(6,kernel_size=(5,5),activation='tanh',padding='valid',input_shape=(32,32,1)))
model.add(AveragePooling2D(pool_size=(2,2),strides=2,padding='valid'))

model.add(Conv2D(16,kernel_size=(5,5),activation='tanh',padding='valid'))
model.add(AveragePooling2D(pool_size=(2,2),strides=2,padding='valid'))

model.add(Flatten())

model.add(Dense(120,activation='tanh'))
model.add(Dense(84,activation='tanh'))
model.add(Dense(10,activation='softmax'))

model.summary()

model.compile(loss='sparse_categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

model.fit(X_train,y_train,epochs=100,batch_size=32,verbose=1,validation_data=(X_test,y_test))

