# -*- coding: utf-8 -*-
"""1_Perceptron.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10KG9Ie81I2LXZ9ZYsoaRs7cT9NGfaijA
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.linear_model import Perceptron

data = pd.read_csv(r'D:\CODING_CODES\AIML\Deep Learning\Theory\Data\placement.csv')

data.sample(10)

sns.scatterplot(x=data['cgpa'],y=data['resume_score'],hue=data['placed'])
plt.show()

X = data.drop(['placed'],axis=1)
y = data['placed']

percep = Perceptron()

percep.fit(X,y)

print(percep.coef_) # weights

print(percep.intercept_)  # bias

from mlxtend.plotting import plot_decision_regions

plot_decision_regions(X.values,y.values,clf=percep,legend=1)
plt.show()

