# -*- coding: utf-8 -*-
"""pretrained-models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nW28ND1wky3GjoWlU_x0MRsff03PzgLG
"""

import tensorflow
from tensorflow import keras
from keras.applications.resnet50 import ResNet50, preprocess_input, decode_predictions
from keras.preprocessing import image
import numpy as np

model = ResNet50(weights='imagenet')

img1_path = '/content/bread.jpeg'
img1 = image.load_img(img1_path,target_size=(224,224))
x1 = image.img_to_array(img1)
x1 = np.expand_dims(x1,axis=0)
x1 = preprocess_input(x1)
pred1 = model.predict(x1)
print('Predicted: ',decode_predictions(pred1,top=3)[0])

img2_path = '/content/car.jpeg'
img2 = image.load_img(img2_path,target_size=(224,224))
x2 = image.img_to_array(img2)
x2 = np.expand_dims(x2,axis=0)
x2 = preprocess_input(x2)
pred2 = model.predict(x2)
print('Predicted: ',decode_predictions(pred2,top=3)[0])

