# -*- coding: utf-8 -*-
"""transfer_learning_feature_extraction_noDataAug.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nwxzOwa727F9QeIOjB0a7Kihu96uYlgS
"""

import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import *
from keras.applications.vgg16 import VGG16

import kagglehub

# Download latest version
path = kagglehub.dataset_download("salader/dogs-vs-cats")

print("Path to dataset files:", path)

!mv /root/.cache/kagglehub/datasets/salader/dogs-vs-cats/versions/1 /content/cat_dog

conv_base = VGG16(
    weights = 'imagenet',
    include_top = False,
    input_shape = (150,150,3)
)

conv_base.summary()

model = Sequential()
model.add(conv_base)
model.add(Flatten())
model.add(Dense(256,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.summary()

conv_base.trainable = False

# generators test
train_ds = keras.utils.image_dataset_from_directory(
    directory = '/content/cat_dog/train',
    labels = 'inferred',
    label_mode = 'int',
    batch_size = 32,
    image_size = (150,150)
)

# generators train
test_ds = keras.utils.image_dataset_from_directory(
    directory = '/content/cat_dog/test',
    labels = 'inferred',
    label_mode = 'int',
    batch_size = 32,
    image_size = (150,150)
)

# normalize
def process(img,label):
  img = tf.cast(img/255,tf.float32)
  return img,label
train_ds = train_ds.map(process)
test_ds = test_ds.map(process)

model.compile(optimizer = 'Adam', loss='binary_crossentropy',metrics=['accuracy'])

model.fit(x=train_ds,validation_data=test_ds,batch_size=32,epochs=10,verbose=1)

