# -*- coding: utf-8 -*-
"""transfer-learning-fine-tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5mL30aekCZK7xH2u5N17YKKmSr-1OS6
"""

import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import *
from keras.applications.vgg16 import VGG16

import kagglehub

# Download latest version
path = kagglehub.dataset_download("salader/dogs-vs-cats")

print("Path to dataset files:", path)

conv_base = VGG16(
    weights = 'imagenet',
    include_top = False,
    input_shape = (150,150,3)
)

conv_base.trainable = True
set_trainable = False
for layer in conv_base.layers:
  if layer.name == 'block5_conv1':
    set_trainable = True
  if set_trainable:
    layer.trainable = True
  else:
    layer.trainable = False

for layer in conv_base.layers:
  print(f'{layer.name} -> {layer.trainable}')

conv_base.summary()

model = Sequential()
model.add(conv_base)
model.add(Flatten())
model.add(Dense(256,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

train_ds = keras.utils.image_dataset_from_directory(
    directory = '/kaggle/input/dogs-vs-cats/train',
    labels = 'inferred',
    label_mode = 'int',
    image_size= (150,150),
    batch_size=32
)

test_ds = keras.utils.image_dataset_from_directory(
    directory = '/kaggle/input/dogs-vs-cats/test',
    labels = 'inferred',
    label_mode = 'int',
    image_size= (150,150),
    batch_size=32
)

def process(img,label):
  img = tf.cast(img/255,tf.float32)
  return img,label
train_data = train_ds.map(process)
test_data = test_ds.map(process)

model.compile(
    optimizer = keras.optimizers.RMSprop(learning_rate=1e-5),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(x=train_data,validation_data=test_data,epochs=5)

