# -*- coding: utf-8 -*-
"""transfer_learning_feature_extraction_withDataAug.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13UuhRMz8QPRsVxo5qT-v2DREzMUdOui2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import *
from keras.applications.vgg16 import VGG16

conv_base = VGG16(
    include_top = False,
    weights = 'imagenet',
    input_shape = (150,150,3)
)
model = Sequential()
model.add(conv_base)
model.add(Flatten())
model.add(Dense(256,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

import kagglehub

# Download latest version
path = kagglehub.dataset_download("salader/dogs-vs-cats")

print("Path to dataset files:", path)

!mv /kaggle/input/dogs-vs-cats /content/cat_dog

from tensorflow.keras.preprocessing.image import ImageDataGenerator, img_to_array, array_to_img, load_img

train_datagen = ImageDataGenerator(
    rescale=1./255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
)
test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    '/content/cat_dog/train',
    target_size=(150,150),
    batch_size=32,
    class_mode = 'binary'
)
validation_generator = test_datagen.flow_from_directory(
    '/content/cat_dog/test',
    target_size=(150,150),
    batch_size=32,
    class_mode = 'binary'
)

model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

history = model.fit(train_generator,epochs=5,validation_data=validation_generator)

