# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qaol_IArZoaKymQEax08QYbxggg3hzoB
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df = pd.read_csv('/content/multivariate_linear_regression_data.csv')
print(df.head())

print(df.info())

X = df.drop('Salary',axis=1)
y = df['Salary']

print(X.head())

print(y.head())

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=5)

print(X_train.info())

lr = LinearRegression()

lr.fit(X_train,y_train)

prediction = X_test.iloc[[0]]
# returns a dataframe of 2D dimension
# X_test.iloc[0] returns a series and hence dimension is 1D
# for multivariate linear regression, we need 2D value
print(lr.predict(prediction))

print(y_test.head())

print(lr.coef_)

print(lr.intercept_)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
y_pred = lr.predict(X_test)
mae = mean_absolute_error(y_test,y_pred)
print(mae)

mse = mean_squared_error(y_test,y_pred)
print(mse)

rmse = np.sqrt(mse)
print(rmse)

r2 = r2_score(y_test,y_pred)
print(r2)

import joblib

# Function to predict salary for new input
def predict_salary(input_data, model):
    """
    input_data: dict with keys ['Experience','EducationScore','Certifications']
    model: trained LinearRegression model
    """
    # Convert dict to DataFrame
    df = pd.DataFrame([input_data])

    # Ensure 2D input for prediction
    salary_pred = model.predict(df)

    return salary_pred[0]

# Function to save the trained linear regression model
def save_lr_model(model, path='linear_regression_model.pkl'):
    joblib.dump(model, path)
    print(f'Model saved as {path}')

# Example new person
new_person = {
    'Experience': 10,
    'EducationScore': 25,
    'Certifications': 2
}

# Predict salary
predicted_salary = predict_salary(new_person, lr)
print(f"Predicted Salary: {predicted_salary}")

# Save trained model
save_lr_model(lr)

