# -*- coding: utf-8 -*-
"""ColumnTransformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wK5EwUtO1sBu2S-644gVx70RvuRu8AWM
"""

import pandas as pd
import numpy as np

df = pd.read_csv(r'D:\CODING_CODES\AIML\ML\Feature Engineering\Data\covid_toy.csv')

print(df.sample(10))

print(df.info())

print(df.isnull().sum())

from sklearn.model_selection import train_test_split
X = df.drop(columns=['has_covid'],axis=1)
y = df['has_covid']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=4)

# fever -> SimpleImputer() to handle null values by mean of values
# gender, city -> OneHotEncoder() for nominal encoding
# cough -> OrdinalEncoder() for ordinal encoding
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder

from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ('tnsf1',SimpleImputer(),['fever']),
    ('tnsf2',OneHotEncoder(sparse_output=False,dtype=np.int32,drop='first'),['gender','city']),
    ('tnsf3',OrdinalEncoder(categories=[['Mild','Strong']]),['cough'])
],remainder='passthrough')

X_train_new = transformer.fit_transform(X_train)

X_test_new = transformer.transform(X_test)

print(X_train.shape)
print(X_train_new.shape)

