# -*- coding: utf-8 -*-
"""OneHotEncoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Atxx0GQSw8sG6_iXabMb7du_ktu6lryb
"""

import pandas as pd
import numpy as np

df = pd.read_csv(r'D:\CODING_CODES\AIML\ML\Feature Engineering\Data\cars.csv')

print(df.sample(5))

print(df['fuel'].unique())

# OHE by pandas
pd.get_dummies(df,columns=['fuel','owner'])

# Removing one column to ensure multicolinearity
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

# OHE by Scikit learn
from sklearn.model_selection import train_test_split
X = df.iloc[:,0:4]
y = df.iloc[:,-1]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=4)

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

print(X_train_new)

print(type(X_train_new))

# merging new X_train with original data
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

