# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192X2p0TdlnWCOiWUnU7UPWQxZmCeE1Cq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv(r'D:\CODING_CODES\AIML\ML\Feature Engineering\Data\customer.csv')
print(df.head())

df = df.loc[:,'review':'purchased']

print(df.head())

from sklearn.model_selection import train_test_split
X = df.drop('purchased',axis=1)
y = df['purchased']
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=4)

print(X_train)

from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

oe.fit(X_train)

X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

print(X_train)

X_train = pd.DataFrame(X_train,columns=X.columns)
X_test = pd.DataFrame(X_test,columns=X.columns)

print(X_train.head())

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()   #  only for output column y

le.fit(y_train)

y_train = le.transform(y_train)
y_test = le.transform(y_test)

print(y_train)

y_train = pd.DataFrame(y_train,columns=['purchased'])
y_test = pd.DataFrame(y_test,columns=['purchased'])

print(y_train)

