# -*- coding: utf-8 -*-
"""MultiVariateLinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R0pI5sonNNAe-IBKp_5jgAM8PFhwuZs1
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df = pd.read_csv(r'D:\CODING_CODES\AIML\ML\Supervised\Data\multivariate_linear_regression_data.csv')
print(df.head())

print(df.info())

X = df.drop('Salary',axis=1)
y = df['Salary']

print(X.head())

print(y.head())

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=5)

print(X_train.info())

lr = LinearRegression()

lr.fit(X_train,y_train)

prediction = X_test.iloc[[0]]
# returns a dataframe of 2D dimension
# X_test.iloc[0] returns a series and hence dimension is 1D
# for multivariate linear regression, we need 2D value
print(lr.predict(prediction))

print(y_test.head())

print(lr.coef_)

print(lr.intercept_)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
y_pred = lr.predict(X_test)
mae = mean_absolute_error(y_test,y_pred)
print(mae)

mse = mean_squared_error(y_test,y_pred)
print(mse)

rmse = np.sqrt(mse)
print(rmse)

r2 = r2_score(y_test,y_pred)
print(r2)

