# -*- coding: utf-8 -*-
"""Regularization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CE7bfmq8lG3aQmvFe-pNn-Wuu1QMK-eG
"""

from sklearn.linear_model import Ridge, Lasso, LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)
X = np.random.rand(100, 1) * 100
y = 2.5 * X.squeeze() + np.random.randn(100) * 50

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=5)

linear_regressor = LinearRegression()
linear_regressor.fit(X_train,y_train)
y_pred_linear = linear_regressor.predict(X_test)

r2_linear = r2_score(y_test,y_pred_linear)
print(r2_linear)

ridge_regressor = Ridge(alpha=100)
ridge_regressor.fit(X_train,y_train)
y_pred_ridge = ridge_regressor.predict(X_test)

r2_ridge = r2_score(y_test,y_pred_ridge)
print(r2_ridge)

lasso_regressor = Lasso(alpha=50)
lasso_regressor.fit(X_train,y_train)
y_pred_lasso = lasso_regressor.predict(X_test)

r2_lasso = r2_score(y_test,y_pred_lasso)
print(r2_lasso)

plt.scatter(X,y)
plt.plot(X_train,linear_regressor.predict(X_train),color='red',linewidth=5)
plt.plot(X_train,ridge_regressor.predict(X_train),color='blue',linewidth=3)
plt.plot(X_train,lasso_regressor.predict(X_train),color='green')
plt.show()

