# -*- coding: utf-8 -*-
"""SVC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oInLueZX7Wg_Pqqd_K2-2Ve-eJrQqiIC
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('D:\CODING_CODES\AIML\ML\Supervised\Data\svm_practice_100.csv')

df = df.drop('ID',axis=1)

df.info()

X = df.drop('Decision',axis=1)
y = df['Decision']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

encoder = LabelEncoder()
y_train_transformed = encoder.fit_transform(y_train)
y_test_transformed = encoder.transform(y_test)

svc_model = SVC()

params = {
    'C':[1,2,3,4,5,6,7,8,9,10],
    'kernel':['linear','poly','rbf','sigmoid'],
    'degree':[1,2,3,4,5,6],
    'gamma':['scale','auto']
}

model = GridSearchCV(svc_model,param_grid=params,cv=5,scoring='accuracy')

model.fit(X_train,y_train_transformed)

model.best_params_

accuracy = accuracy_score(y_test_transformed,model.predict(X_test))
accuracy

def plot_decision_boundary(model, X, y):
    h = 0.01
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                         np.arange(y_min, y_max, h))
    Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)

    plt.contourf(xx, yy, Z, cmap=plt.cm.coolwarm, alpha=0.8)
    plt.scatter(X[:, 0], X[:, 1], c=y, cmap=plt.cm.coolwarm, edgecolors='k')
    plt.xlabel('Exam Score')
    plt.ylabel('Interview Score')
    plt.title('SVM Decision Boundary')
    plt.show()

plot_decision_boundary(model, X_train, y_train_transformed)

