# -*- coding: utf-8 -*-
"""svcNonLinear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BsDcQ5piAWdIyITS1K1SBTd63MMFzOce
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from mlxtend.plotting import plot_decision_regions

df = pd.read_csv(r'D:\CODING_CODES\AIML\ML\Supervised\Data\svm_nonlinear_100.csv')

print(df.sample(10))

df = df.drop('ID',axis=1)

X = df.drop('Decision',axis=1)
y = df['Decision']

class_0 = df[df['Decision'] == 'Class_0']
class_1 = df[df['Decision'] == 'Class_1']

# Plot
plt.figure(figsize=(8, 6))
plt.scatter(class_0['Feature_1'], class_0['Feature_2'], color='red', label='Class 0')
plt.scatter(class_1['Feature_1'], class_1['Feature_2'], color='blue', label='Class 1')
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.title('Non-linear Dataset Scatter Plot')
plt.legend()
plt.show()

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=43)

encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

svc = SVC()

params = {
    'C':[1,2,3,4,5,6,7,8,9,10],
    'kernel':['linear','poly','rbf','sigmoid'],
    'degree':[1,2,3,4,5,6,7,8,9],
    'gamma':['auto','scale']
}

model = GridSearchCV(svc, param_grid = params, cv=5, scoring='accuracy')

model.fit(X_train,y_train_encoded)

model.best_params_

accuracy = accuracy_score(y_test_encoded,model.predict(X_test))
accuracy

plot_decision_regions(X_train.values, y_train_encoded, clf=model, legend=2)

plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.title('SVM Decision Boundary using mlxtend')
plt.show()

